// Chat action types
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const CLEAR_ACTIVE_CHAT = 'CLEAR_ACTIVE_CHAT';

export const LOAD_MESSAGES_REQUEST = 'LOAD_MESSAGES_REQUEST';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAILURE = 'LOAD_MESSAGES_FAILURE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const SET_TYPING_STATUS = 'SET_TYPING_STATUS';
export const CLEAR_TYPING_STATUS = 'CLEAR_TYPING_STATUS';

export const LOAD_CONVERSATIONS_REQUEST = 'LOAD_CONVERSATIONS_REQUEST';
export const LOAD_CONVERSATIONS_SUCCESS = 'LOAD_CONVERSATIONS_SUCCESS';
export const LOAD_CONVERSATIONS_FAILURE = 'LOAD_CONVERSATIONS_FAILURE';

export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';

// Active users from WebSocket
export const SET_ACTIVE_USERS = 'SET_ACTIVE_USERS';
export const UPDATE_ACTIVE_USERS = 'UPDATE_ACTIVE_USERS';

// Mark messages as read
export const MARK_MESSAGES_AS_READ = 'MARK_MESSAGES_AS_READ';
