// Friend action types
export const LOAD_FRIENDS_REQUEST = 'LOAD_FRIENDS_REQUEST';
export const LOAD_FRIENDS_SUCCESS = 'LOAD_FRIENDS_SUCCESS';
export const LOAD_FRIENDS_FAILURE = 'LOAD_FRIENDS_FAILURE';

export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const DECLINE_FRIEND_REQUEST = 'DECLINE_FRIEND_REQUEST';
export const CANCEL_FRIEND_REQUEST = 'CANCEL_FRIEND_REQUEST';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const UPDATE_FRIEND_STATUS = 'UPDATE_FRIEND_STATUS';
