// WebSocket action types
export const WS_CHAT_CONNECTED = 'WS_CHAT_CONNECTED';
export const WS_CHAT_DISCONNECTED = 'WS_CHAT_DISCONNECTED';
export const WS_CHAT_SET_CLIENT = 'WS_CHAT_SET_CLIENT';
export const WS_NOTIFICATION_CONNECTED = 'WS_NOTIFICATION_CONNECTED';
export const WS_NOTIFICATION_DISCONNECTED = 'WS_NOTIFICATION_DISCONNECTED';
export const WS_NOTIFICATION_SET_CLIENT = 'WS_NOTIFICATION_SET_CLIENT';
